#!/bin/python3
import rsa_factoring as rf

def main():
    lines = rf.getlines()
    for line in lines:
        n = int(line.strip())
        p, q = rf.factorize_number(n)
        if p and q:
            print(f"{n}={q}*{p}")


if __name__ == "__main__":
    main()
